# -*- coding: utf-8 -*-
"""movie recommendation data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ZcBOPiucpoR4JfKnvh0JUIUJHBeR-og
"""

import numpy as np
import pandas as pd

from google.colab import drive

drive.mount('/content/drive')

movies = pd.read_csv('/content/drive/MyDrive/movie_rec/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/drive/MyDrive/movie_rec/tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)

movies =movies.merge(credits,on='title')

movies.head(1)

# genres
# id
# keywords
# title
# overview
# cast
# crew

movies= movies[['movie_id','title','overview','genres','keywords','cast','crew' ]]

movies.head()

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

movies.iloc[0].genres

import ast
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

movies['genres'].apply(convert)

movies['genres']= movies['genres'].apply(convert)

movies.head()

movies['keywords'] = movies['keywords'].apply(convert)

movies.head()

import ast
def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter !=3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

movies['cast']= movies['cast'].apply(convert3)

movies.head()

import ast
def fetch_director(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      L.append(i['name'])
      break
  return L

movies['crew']=movies['crew'].apply(fetch_director)

movies.head()

movies['overview']=movies['overview'].apply(lambda x:x.split())

movies.head()

movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

movies.head()

movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

movies.head()

dataframe = movies[['movie_id','title','tags']]

dataframe['tags']= dataframe['tags'].apply(lambda x:" ".join(x))

dataframe.head()

import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y= []
  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

dataframe['tags'].apply(stem)

dataframe['tags'][0]

dataframe['tags']= dataframe['tags'].apply(lambda x:x.lower())

dataframe.head()

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(dataframe['tags']).toarray()

vectors[0]

cv.get_feature_names_out()

ps.stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

sorted(list(enumerate(similarity[0])),reverse=True, key=lambda x:x[1])[1:6]

def recommend(movie):
  movie_index= dataframe[dataframe['title']==movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]

  for i in  movies_list:
    print(dataframe.iloc[i[0]].title)

recommend('Batman')

recommend('Zodiac')

recommend('Coffee Town')

